/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testclass;

/** 42 - 13
 *
 * @author cmaso
 */
public class Embeded_Resource {
 public  static String DefaultF[] = {
"- - - - - - - - l l l - - - - - - - l l l - - - - - - - - - " ,
"- - - - - - - - l l l - - - - - - - l l l - - - - - - - - - ",
"- - - - - - - l W W W l - - - - - l l l l l - - - - - - - - " ,
"- - - - - - - l W W W l l l l l l l l l l l - - - - - - - - " ,
"- - - - - - - - l W W W W W W l l l l l l - - - - - - - - - " ,
"- - - - - - - l W W W W W W W l l l l l l l - - - - - - - - " ,
"- - - - - - l W W W W W W W W l l l l l l l l - - - - - - - " ,
"- - - - - - l W W W W W W W W l l l l l Z l l - - - - - - - " ,
"- - - - - - l W W W l l W W W l l R l R l l l - - - - - - - " ,
"- - - - - - l W W W l l W l l l Z l Z l l D l - - - - - - - " ,
"- - - - - - l W W W W W l W l W l l l D W D l - - - - - - - " ,
"- - - - - - l W W W W W l W W W l D W D W l l - - - - - - - " ,
"- - - - - - l D W W W W W l l l W D W D l l l - - - - - - - " ,
"- - - - - - - l D W W W W W l l l l l l l l - - - - - - - - " ,
"- - - - - - l W W W W W W W l l l l l l l l l - - - - - - - " ,
"- - - - - l W W W W W W W W l l l l l l l l D l - - - - - - " ,
"- - - - l W D l W W W W l l l l l l l l l l l D l - - - - - " ,
"- - - l W W l W W W W l W W W W W l l l l l l l l l - - - - " ,
"- - - l W D l W W W l W W W W W W W l l l l l l D l - - - - " ,
"- - - - l l l W W W l W W l W l W W l l l l l l l - - - - - " ,
"- - - - - - l W W W l W W W l W W W l l l l l - - - - - - - " ,
"- - - - - - l W W W l D W l W l W D l l l l l - - - - - - - " ,
"- - - - - - l W W W W l D W W W D l l l l l l - - - - - - - " ,
"- - - - - - l W W W W W l l l l l l l l l l l - - - - - - - " ,
"- - - - - - l D W W W W W W l l l l l l l l l - - - - - - - " ,
"- - - - - - - l D W W W l l l l l l l l l l - - - - - - - - " ,
"- - - - - - - - l W W W l - - - l l l l l - - - - - - - - - " ,
"- - - - - - - - l W W D l - - - l l l l l - - - - - - - - - " ,
"- - - - - - - - - l l l - - - - - l l l - - - - - - - - - - " ,
"- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - " ,
"- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "};
 
 



public static String Default2[] = {
"- - - - - - - - l l l - - - - - - - l l l - - - - - - - - - " ,
"- - - - - - - - l l l - - - - - - - l l l - - - - - - - - - " ,
"- - - - - - - l W W W l - - - - - l l l l l - - - - - - - - " ,
"- - - - - - - l W W W l l l l l l l l l l l - - - - - - - - " ,
"- - - - - - - - l W W W W W W l l l l l l - - - - - - - - - " ,
"- - - - - - - l W W W W W W W l l l l l l l - - - - - - - - " ,
"- - - - - - l W W W W W W W W l l l l l l l l - - - - - - - " ,
"- - - - - - l W W W W W W W W l l l l l R l l - - - - - - - " ,
"- - - - - - l W W W l l W W W l l Z l Z l l l - - - - - - - " ,
"- - - - - - l W W W l l W l l l R l R l l D l - - - - - - - " ,
"- - - - - - l W W W W W l W l W l l l D W D l - - - - - - - " ,
"- - - - - - l W W W W W l W W W l D W D W l l - - - - - - - " ,
"- - - - - - l D W W W W W l l l W D W D l l l - - - - - - - " ,
"- - - - - - - l D W W W W W l l l l l l l l - - - - - - - - " ,
"- - - - - - l W W W W W W W l l l l l l l l l - - - - - - - " ,
"- - - - - l W W W W W W W W l l l l l l l l D l - - - - - - " ,
"- - - - l W D l W W W W l l l l l l l l l l l D l - - - - - " ,
"- - - l W W l W W W W l W W W W W l l l l l l l l l - - - - " ,
"- - - l W D l W W W l W W W W W W W l l l l l l D l - - - - " ,
"- - - - l l l W W W l W W l W l W W l l l l l l l - - - - - " ,
"- - - - - - l W W W l W W W l W W W l l l l l - - - - - - - " ,
"- - - - - - l W W W l D W l W l W D l l l l l - - - - - - - " ,
"- - - - - - l W W W W l D W W W D l l l l l l - - - - - - - " ,
"- - - - - - l W W W W W l l l l l l l l l l l - - - - - - - " ,
"- - - - - - l D W W W W W W l l l l l l l l l - - - - - - - " ,
"- - - - - - - l D W W W l l l l l l l l l l - - - - - - - - " ,
"- - - - - - - - l W W W l - - - l l l l l - - - - - - - - - " ,
"- - - - - - - - l W W D l - - - l l l l l - - - - - - - - - " ,
"- - - - - - - - - l l l - - - - - l l l - - - - - - - - - - " ,
"- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - " ,
"- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "};

public static String Default3[] = {
"- - - - - - - - l l l - - - - - - - l l l - - - - - - - - - " ,
"- - - - - - - - l l l - - - - - - - l l l - - - - - - - - - " ,
"- - - - - - - l W W W l - - - - - l l l l l - - - - - - - - " ,
"- - - - - - - l W W W l l l l l l l l l l l - - - - - - - - " ,
"- - - - - - - - l W W W W W W l l l l l l - - - - - - - - - " ,
"- - - - - - - l W W W W W W W l l l l l l l - - - - - - - - " ,
"- - - - - - l W W W W W W W W l l l l l l l l - - - - - - - " ,
"- - - - - - l W W W W W W W W l l l l l Z l l - - - - - - - " ,
"- - - - - - l W W W l l W W W l l R l Z l l l - - - - - - - " ,
"- - - - - - l W W W l l W l l l Z l R l l D l - - - - - - - " ,
"- - - - - - l W W W W W l W l W l l l D W D l - - - - - - - " ,
"- - - - - - l W W W W W l W W W l D W D W l l - - - - - - - " ,
"- - - - - - l D W W W W W l l l W D W D l l l - - - - - - - " ,
"- - - - - - - l D W W W W W l l l l l l l l - - - - - - - - " ,
"- - - - - - l W W W W W W W l l l l l l l l l - - - - - - - " ,
"- - - - - l W W W W W W W W l l l l l l l l D l - - - - - - " ,
"- - - - l W D l W W W W l l l l l l l l l l l D l - - - - - " ,
"- - - l W W l W W W W l W W W W W l l l l l l l l l - - - - " ,
"- - - l W D l W W W l W W W W W W W l l l l l l D l - - - - " ,
"- - - - l l l W W W l W W l W l W W l l l l l l l - - - - - " ,
"- - - - - - l W W W l W W W l W W W l l l l l - - - - - - - " ,
"- - - - - - l W W W l D W l W l W D l l l l l - - - - - - - " ,
"- - - - - - l W W W W l D W W W D l l l l l l - - - - - - - " ,
"- - - - - - l W W W W W l l l l l l l l l l l - - - - - - - " ,
"- - - - - - l D W W W W W W l l l l l l l l l - - - - - - - " ,
"- - - - - - - l D W W W l l l l l l l l l l - - - - - - - - " ,
"- - - - - - - - l W W W l - - - l l l l l - - - - - - - - - " ,
"- - - - - - - - l W W D l - - - l l l l l - - - - - - - - - " ,
"- - - - - - - - - l l l - - - - - l l l - - - - - - - - - - " ,
"- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - " ,
"- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "};

public static String L1[] = {
"- - - - - - - - - - l l - - - l l l - - - - - - - - - - - - ",
"- - - - - - - - - - l l - - - l l l - - - - - - - - - - - - ", 
"- - - - - - - - - l W W l - l l l l l - - - - - - - - - - - ",
"- - - - - - - - l W W W l - l l l l l - - - - - - - - - - - ",
"- - - - - - - l l l l l l l l l l l - - - - - - - - - - - - ",
"- - - - - - l l l l l l l l l l l l l - - - - - - - - - - - ",
"- - - - - l l l l l l l l l l l l l l l - - - - - - - - - - ",
"- - - - - l l l l Z l l l l l l l l l l - - - - - - - - - - ",
"- - - - - l R l R l l l l l l l l l l l - - - - - - - - - - ",
"- - - - - Z l Z l l D l l l l l l l l l - - - - - - - - - - ",
"- - - - l l l l D W l l l l l l l l l l - - - - - - - - - - ",
"- - - - l l D W D W l l l l l l l l l l - - - - - - - - - - ",
"- - - - l W D W D l l l l l l l l l l - - - - - - - - - - - ",
"- - - - - l l l l l l l l l l l l l - - - - - - - - - - - - ",
"- - - - - - l l l l l l l l l l l - - - - - - - - - - - - - ",
"- - - - - D l l l l l l l l l l l l - - - - - - - - - - - - ",
"- - - - l l l l l l l l l l l l l l l - - - - - - - - - - - ",
"- - - l W W W l l l l l l l l l l l l - - - - - - - - - - - ",
"- - - l W W W W l l l l l l D l l l l - - - - - - - - - - - ",
"- - - l W l W W l l l l l D l l l l l - - - - - - - - - - - ",
"- - - l l W W W l l l l l l l l l l l - - - - - - - - - - - ",
"- - - l W l W W l l l D l l l l l l l - - - - - - - - - - - ",
"- - - l W W W D l l l l l l l l l l l - - - - - - - - - - - ",
"- - - l W W D l l l l l l l l l l l l - - - - - - - - - - - ",
"- - - - l l l l l l l l l l l l l l - - - - - - - - - - - - ",
"- - - l l l l l l l l l l l l l l - - - - - - - - - - - - - ",
"- - - l l l l l l - - l l W W W l - - - - - - - - - - - - - ",
"- - - l l l l l - - - l W W W W l - - - - - - - - - - - - - ",
"- - - - l l l - - - - l W W W W l - - - - - - - - - - - - - ",
"- - - - - - - - - - - - l l l l - - - - - - - - - - - - - - ",
"- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "};

public static String L2[] = {
"- - - - - - - - - - - - l l - - - l l l - - - - - - - - - - ",
"- - - - - - - - - - - - l l - - - l l l - - - - - - - - - - ", 
"- - - - - - - - - - - l W W l - l l l l l - - - - - - - - - ",
"- - - - - - - - - - l W W W l - l l l l l - - - - - - - - - ",
"- - - - - - - - - l l l l l l l l l l l - - - - - - - - - - ",
"- - - - - - - - l l l l l l l l l l l l l - - - - - - - - - ",
"- - - - - - - l l l l l l l l l l l l l l l - - - - - - - - ",
"- - - - - - - l l l l Z l l l l l l l l l l - - - - - - - - ",
"- - - - - - - l R l R l l l l l l l l l l l - - - - - - - - ",
"- - - - - - - Z l Z l l D l l l l l l l l l - - - - - - - - ",
"- - - - - - l l l l D W l l l l l l l l l l - - - - - - - - ",
"- - - - - - l l D W D W l l l l l l l l l l - - - - - - - - ",
"- - - - - - l W D W D l l l l l l l l l l - - - - - - - - - ",
"- - - - - - - l l l l l l l l l l l l l - - - - - - - - - - ",
"- - - - - - - - l l l l l l l l l l l - - - - - - - - - - - ",
"- - - - - - - D l l l l l l l l l l l l - - - - - - - - - - ",
"- - - - - - l l l l l l l l l l l l l l l - - - - - - - - - ",
"- - - - - l W W W l l l l l l l l l l l l - - - - - - - - - ",
"- - - - - l W W W W l l l l l l l l l l l - - - - - - - - - ",
"- - - - - l W l W W l l l l l l l D l l l - - - - - - - - - ",
"- - - - - l l W W W l l l l l l D l l l l - - - - - - - - - ",
"- - - - - l W l W W l l l l l l l l l l l - - - - - - - - - ",
"- - - - - l W W W D l l l l D l l l l l l - - - - - - - - - ",
"- - - - - l W W D l l l l l l l l l l l l - - - - - - - - - ",
"- - - - - - l l l l l l l l l l l l l l - - - - - - - - - - ",
"- - - - - l l W W W l l l l l l l l l - - - - - - - - - - - ",
"- - - - - l W W W W l - - l l l l l l - - - - - - - - - - - ",
"- - - - - l W W W l - - - l l l l l l - - - - - - - - - - - ",
"- - - - - - l l l - - - - l l l l l l - - - - - - - - - - - ",
"- - - - - - - - - - - - - - l l l l - - - - - - - - - - - - ",
"- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "};

public static String R1[]= {
"- - - - - - - - - - - l l - - - l l - - - - - - - - - - - - ",
"- - - - - - - - - - - l l - - - l l - - - - - - - - - - - - ",
"- - - - - - - - - - l l l l - l W W l - - - - - - - - - - - ",
"- - - - - - - - - - l l l l - l W W W l - - - - - - - - - - ",
"- - - - - - - - - - - l l l l l l l l l l - - - - - - - - - ",
"- - - - - - - - - - l W W W W W W W W W l l - - - - - - - - ",
"- - - - - - - - - l l W W W W W W W W W W l l - - - - - - - ",
"- - - - - - - - - l W W W W W W W W W W W W l - - - - - - - ",
"- - - - - - - - - l W W W W W W W W W W W W l - - - - - - - ",
"- - - - - - - - - l W W W W W W W l l W W W l - - - - - - - ",
"- - - - - - - - - l W W W W W W W l l W l l l - - - - - - - ",
"- - - - - - - - - l W W W W W W W W W l W l W l - - - - - - ",
"- - - - - - - - - l W W W W W W W W W l W W W l - - - - - - ",
"- - - - - - - - - - l W W W W W W W W l l l l - - - - - - - ",
"- - - - - - - - - - - l W W W W W W W W l - - - - - - - - - ",
"- - - - - - - - - - - l W W l W W W W W W l - - - - - - - - ",
"- - - - - - - - - - l l W W W l W W W W W l l - - - - - - - ",
"- - - - - - - - - - l W l W W W l W W l l W W l - - - - - - ",
"- - - - - - - - - - l W W l W W W l W l W W W W l - - - - - ",
"- - - - - - - - - - l W W W l W W l W l W W l W l - - - - - ",
"- - - - - - - - - - l W W W W l l W W l W W W l l - - - - - ",
"- - - - - - - - - - l W W W W W W W W l W W l W l - - - - - ",
"- - - - - - - - - - l W W W W W W W W l D W W W l - - - - - ",
"- - - - - - - - - - l W W W W W W W W l l D W W l - - - - - ",
"- - - - - - - - - - - l W W W W l l l W l l l l - - - - - - ",
"- - - - - - - - - - - - l l l l l l l l W W W l l - - - - - ",
"- - - - - - - - - - - - l l l l l - - l W W W W l - - - - - ",
"- - - - - - - - - - - - l l l l l - - - l W W W l - - - - - ",
"- - - - - - - - - - - - l l l l - - - - - l l l - - - - - - ",
"- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ",
"- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "};

public static String R2[] = {
"- - - - - - - - - - - l l - - - l l - - - - - - - - - - - - ",
"- - - - - - - - - - - l l - - - l l - - - - - - - - - - - - ",
"- - - - - - - - - - l l l l - l W W l - - - - - - - - - - - ",
"- - - - - - - - - - l l l l - l W W W l - - - - - - - - - - ",
"- - - - - - - - - - - l l l l l l l l l l - - - - - - - - - ",
"- - - - - - - - - - l W W W W W W W W W l l - - - - - - - - ",
"- - - - - - - - - l l W W W W W W W W W W l l - - - - - - - ",
"- - - - - - - - - l W W W W W W W W W W W W l - - - - - - - ",
"- - - - - - - - - l W W W W W W W W W W W W l - - - - - - - ",
"- - - - - - - - - l W W W W W W W l l W W W l - - - - - - - ",
"- - - - - - - - - l W W W W W W W l l W l l l - - - - - - - ",
"- - - - - - - - - l W W W W W W W W W l W l W l - - - - - - ",
"- - - - - - - - - l W W W W W W W W W l W W W l - - - - - - ", 
"- - - - - - - - - - l W W W W W W W W l l l l - - - - - - - ",
"- - - - - - - - - - - l W W W W W W W W l - - - - - - - - - ",
"- - - - - - - - - - - l W W W W W W W W W l - - - - - - - - ",
"- - - - - - - - - - l W W l W W W W W W W l l - - - - - - - ",
"- - - - - - - - - - l W W W l W W W W l l W W l - - - - - - ",
"- - - - - - - - - - l l W W W l W W W l W W W W l - - - - - ",
"- - - - - - - - - - l W l W W W l W W l W W l W l - - - - - ",
"- - - - - - - - - - l W W l W W l W W l W W W l l - - - - - ",
"- - - - - - - - - - l W W W l l W W W l W W l W l - - - - - ",
"- - - - - - - - - - l W W W W W W W W l D W W W l - - - - - ",
"- - - - - - - - - - l W W W W W W W W l l D W W l - - - - - ",
"- - - - - - - - - - - l W W W W W l l l l l l l - - - - - - ",
"- - - - - - - - - - - - l W W W l l l l l l l l l - - - - - ",
"- - - - - - - - - - - - l W W W l - - l l l l l l - - - - - ", 
"- - - - - - - - - - - - l W W W l - - - l l l l l - - - - - ", 
"- - - - - - - - - - - - l l l l - - - - - l l l - - - - - - ", 
"- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ", 
"- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - "};
        
        };